service: notes-api

provider:
  name: aws
  runtime: nodejs18.x

# package:
#   individually: true

functions:
  notes_api:
    handler: src/lambdas/api/index.handler
    package:
      include:
        - src/constants/**
        - src/middlewares/**
        - src/utils/**

plugins:
  - serverless-plugin-typescript
