name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Backend dependencies
        run: npm ci

      - name: Lint code
        run: |
          npm run lint

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: |
          export TF_VAR_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}
          export TF_VAR_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export TF_VAR_openai_api_key=${{ secrets.OPENAI_API_KEY }}
          terraform -chdir=./.aws init -backend-config="bucket=notes-api-terraform" -backend-config="key=notes-api.tfstate" -backend-config="region=us-east-1"

      - name: Terraform Apply
        id: apply
        run: |
          export TF_VAR_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}
          export TF_VAR_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export TF_VAR_openai_api_key=${{ secrets.OPENAI_API_KEY }}
          terraform -chdir=./.aws apply -auto-approve
